[package]
distribution = "2201.8.2"
org = "ballerinax"
name = "googleapis.calendar"
version = "4.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Calendars", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
