name: Pull Request

on: [ pull_request ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Gradle Build without Tests
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: ./gradlew build -x test
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle Build
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: ./gradlew build
        env:
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          REFRESH_URL: ${{ secrets.REFRESH_URL }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          SENDER: ${{ secrets.SENDER }}
          CC: ${{ secrets.CC }}
          ATTACHMENT_PATH: ${{ secrets.ATTACHMENT_PATH }}
          ATTACHMENT_CONTENT_TYPE: ${{ secrets.ATTACHMENT_CONTENT_TYPE }}
          INLINE_IMAGE_PATH: ${{ secrets.INLINE_IMAGE_PATH }}
          INLINE_IMAGE_NAME: ${{ secrets.INLINE_IMAGE_NAME }}
          IMAGE_CONTENT_TYPE: ${{ secrets.IMAGE_CONTENT_TYPE }}
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
